# # # # # # # #
# +--------+  #
# | CONFIG |  #
# +--------+  #
# # # # # # # #

#This is the config for BouncySponge (http://dev.bukkit.org/bukkit-mods/bouncysponge/)


launch: 2.5 #The height players should be launched (I have no testing as to how high the numbers are but 2.5 is default)
#
#  URGENT!
#
# DO NOT SET THE "launch" VALUE TO A NUMBER HIGHER THAN 10!
# DOING SO WILL CAUSE BUKKIT TO SPAM YOUR CONSOLE AND THE PLAYER TO BE STUCK!


configversion: 1