# # # # # # # #
# +--------+  #
# | CONFIG |  #
# +--------+  #
# # # # # # # #

#This is the config for BouncySponge (http://dev.bukkit.org/bukkit-mods/bouncysponge/)


launch: 2.5 #The launch option for height (I have no testing as to how high the numbers are but 2.5 is default (Please always make ti something.5)
#       /\
#       |
#       Must always end in .5
