name: BouncySponge
main: com.adencraft2000.bouncysponge.BouncySponge
authors: [adencraft2000 and kamehameha1]
version: 1.7
description: Makes sponges bouncy

permissions:
    bouncysponge.jump:
        default: true
        description: Will be affected by BouncySponge.

commands:
  bouncysponge:
    description: shows info about bouncysponge
    usage: /bouncysponge
